### ISSUE TITLE
[Docs]: Add github issue & error handling template

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#1]
### ISSUE
- Group:  `server`
- Type: `Docs`
- Time: `1h`
- Priority: `middle`
- Detail: [Docs] Initial Commit 

### TODO
1. [ ] Create commit message template
2. [ ] Create github issue template
3. [ ] Create github error handling template
