### ISSUE TITLE
[Docs]: Initial commit

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#1]
### ISSUE
- Group: `server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create github issue template
2. [x] Create github error handling template
3. [x] Create issue labels
4. [x] Create .editorconfig file
