### ISSUE TITLE
[Refactor]: Refactor tos flow - createTos

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#100]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Add post save hook in TosSchema
2. [x] Optimize TosRepository to save and return data faster
3. [x] Optimize TosService to save and return data faster
