### ISSUE TITLE
[Refactor]: Refactor user flow

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#101]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create findMe, findMeAndUpdate methods in UserController
2. [x] Optimize findByIdAndUpdate method in UserService
2. [x] Delete findUserByIdAndUpdate method in UserController
3. [x] Delete nickName field in UpdateUserDTO
