### ISSUE TITLE
[Feat]: Create AddressModel, UserAddressModel

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#102]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create address.model.ts, user.address.model.ts files in models directory
2. [x] Create and Define AddressModel
3. [x] Create and Define UserAddressModel
