### ISSUE TITLE
[Feat]: Create address dto

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#103]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create address.validator.ts file in validators directory
2. [x] Create and Define validators for CreateAddressDTO
3. [x] Create address.dto.ts file in dtos directory
4. [x] Create and Define CreateAddressDTO
