### ISSUE TITLE
[Feat]: Create user address dto

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#105]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create toObj method in CreateAddressDTO
2. [x] Create user.address.dto.ts file in dtos directory
3. [x] Create and Define CreateUserAddressDTO
4. [x] Create user.address.validator.ts file in validators directory
5. [x] Create and Define user address validators
