### ISSUE TITLE
[Refactor]: Refactor user address model

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#107]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Delete address.model.ts file
2. [x] Define address schema in user.address.model.ts file
3. [x] Change user address schema to contain all the address information
