### ISSUE TITLE
[Feat]: Create user address flow - findMyAddresses

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#109]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create and Define findMyAddresses method in UserAddressController
2. [x] Create and Define findMyAddresses method in UserAddressService
3. [x] Create and Define findMyAddresses method in UserAddressRepository
4. [x] Modify UserAddressResponseInterceptor for checking null condition
