### ISSUE TITLE
[Test]: Test basic controller with Jest

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#11]
### ISSUE
- Group: `Server`
- Type: `Test`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Install supertest
2. [x] Create jest.config.js file and Set configurations
3. [x] Write test cases of basic controller
4. [x] Add test scripts in package.json file
4. [x] Test it
