### ISSUE TITLE
[Feat]: Create user address flow - deleteMyAddress

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#111]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create and Define deleteMyAddress method in UserAddressController
2. [x] Create and Define deleteMyAddress method in UserAddressService
3. [x] Create and Define deleteByIdAndUpdate method in UserAddressRepository
