### ISSUE TITLE
[Feat]: Create user address flow - setMyDefaultAddress

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#112]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `2.0h`
- Priority: `Middle`

### TODO
1. [x] Create and Define ValidAddressIndexDTO in user.address.dto.ts file
2. [x] Create and Define IsAddressIndex validator in user.address.validator.ts file
3. [x] Change the field name from default to defaultAddress in UserAddress schema
4. [x] Add deserialization: defaultAddress in user.address.interceptor.ts file
5. [x] Create and Define setMyDefaultAddress method in UserAddress controller
6. [x] Create and Define setMyDefaultAddress method in UserAddressService
7. [x] Create and Define findByIdAndSetDefault method in UserAddressRepository
