### ISSUE TITLE
[Feat]: Create admin flow - signup

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#116]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create and Define AdminController in admin.controller.ts file
2. [x] Create and Define AdminService in admin.service.ts file
3. [x] Create and Define saveAdmin method in UserRepository
4. [x] Change UserModel to use isMember and role field
