### ISSUE TITLE
[Feat]: Create adminAuthMiddleware

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#119]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Create and Define adminAuthMiddleware in admin.auth.middleware.ts file
2. [x] Change the file name: auth.interface.ts -> index.interface.ts
3. [x] Apply the name changes to other files
