### ISSUE TITLE
[Feat]: Create user model

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#12]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [ ] Create index.ts and users.model.ts files in models directory
2. [ ] Define user model
3. [ ] Make index.ts file to be able to load all other models
