### ISSUE TITLE
[Feat]: Create notice flow

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#121]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `3.0h+`
- Priority: `Middle`

### TODO
1. [x] Create and Define NoticeController
2. [x] Create and Define NoticeService
3. [x] Create and Define NoticeRepository
4. [x] Create and Define NoticeModel
