### ISSUE TITLE
[Feat]: Create faq flow

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#122]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `2.5h`
- Priority: `Middle`

### TODO
1. [x] Create and Define FaqController
2. [x] Create and Define FaqService
3. [x] Create and Define FaqRepository
4. [x] Create and Define FaqModel
5. [x] Create and Define FaqDTOs
6. [x] Create and Define FaqResponseInterceptors
