### ISSUE TITLE
[Feat]: Create express web server with typescript

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#2]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Install typescript, express and other modules needed
2. [x] Create tsconfig.json file and Set compile options
2. [x] Create express web server with typescript
3. [x] Test it
