### ISSUE TITLE
[Feat]: Create express web server

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#2]
### ISSUE
- Group:  `server`
- Type: `Feat`
- Time: `2.0h`
- Priority: `Middle`

### TODO
1. [x] Create mongoDB atlas cluster
2. [x] Create basic express web server
3. [x] Test hello world
