### ISSUE TITLE
[Feat]: Create basic express web server

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#2]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `2.0h`
- Priority: `Middle`

### TODO
1. [x] Create basic express web server using express-cli
2. [x] Create .env file
3. [x] Install babel and Create .babelrc file
4. [x] Test 'hello world'
