### ISSUE TITLE
[Feat]: Create user cache for auth using redis

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#21]
### ISSUE
- Group:  `Server`
- Type: `Feat`
- Time: `2.0h`
- Priority: `High`

### TODO
1. [x] Install redis and bluebird
2. [x] Create user cache for auth using redis
3. [x] Add hooks for cache in user model
3. [x] Apply user cache to auth controller, auth middleware instead user repo
