### ISSUE TITLE
[Refactor]: Refactor basic express web server

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#3]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create src directory
2. [x] Change files' location to src directory
3. [x] Improve router logic
4. [x] Test it
