### ISSUE TITLE
[Feat]: Connect MongoDB Atlas to web server

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#4]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create MongoDB Atlas clusters - test, development, production
2. [x] Install mongoose and Set configuration
3. [x] Connect MongoDB Atlas to web server
4. [x] Test it
