### ISSUE TITLE
[Feat]: Connect mongoDB cluster to express web server

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#4]
### ISSUE
- Group:  `Server`
- Type: `Feat`
- Time: `3.0h+`
- Priority: `High`

### TODO
1. [x] Create mongoDB atlas cluster
2. [x] Install mongoose module
3. [x] Connect cluster to express web server with mongoose
4. [x] Test it
