### ISSUE TITLE
[Feat]: Apply typescript-eslint to project

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#5]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Install eslint, typescript-eslint modules
2. [x] Install eslint vscode extension
3. [x] Create .eslintrc file and Set configurations
4. [x] Create .eslintignore file and Set configurations
5. [x] Test it
