### ISSUE TITLE
[Feat]: Apply prettier to project with eslint

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#6]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Install prettier, eslint-config-prettier and eslint-plugin-prettier
2. [x] Install prettier vscode extension
3. [x] Create .prettierrc file and Set configurations
4. [x] Set prettier configurations in .eslintrc file
4. [x] Test it
