### ISSUE TITLE
[Feat]: Apply lint-staged and husky to project

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#7]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Install lint-staged and husky
2. [x] Create .husky directory and Set pre-commit configurations
3. [x] Create .lintstagedrc.json file and Set configurations
4. [x] Test it
