### ISSUE TITLE
[Refactor]: Refactor user auth

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#71]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Refactor findEmailByMobile, findPasswordByEmailAndMobile using DTOs
2. [x] Create SearchController in search.controller.ts file
3. [x] Move findEmailByMobile, findPasswordByEmailAndMobile to SearchController
