### ISSUE TITLE
[Feat]: Create user flow - findUserByIdAndUpdate

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#73]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Create findUserByIdAndUpdate method in UserController
2. [x] Define findUserByIdANdUpdate
3. [x] Create UpdateUserDTO in user.dto.ts file
4. [x] Change findOneAndUpdate pre hook in user model
5. [x] Change IsPassword validator
