### ISSUE TITLE
[Feat]: Create toc, user toc model

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#74]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create TOC model in toc.model.ts file
2. [x] Create UserTOC model in user.toc.model.ts file
3. [x] Define TOC, UserTOC model
