### ISSUE TITLE
[Feat]: Create tos flow - CreateTOS

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#75]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Change name from TOC to TOS
2. [x] Create TOSController in tos.controller.ts file
3. [x] Define TOSController
4. [x] Create TOSService in tos.service.ts file
5. [x] Define TOSService
6. [x] Create TOSRepository in tos.repository.ts file
7. [x] Define TOSRepository
8. [x] Create IsTOSCode validator in tos.validator.ts file
9. [x] Define IsTOSCode validator
10. [x] Create ValidTOSCodeDTO, CreateTOSDTO in tos.dto.ts file
11. [x] Define ValidTOSCodeDTO, CreateTOSDTO
