### ISSUE TITLE
[Feat]: Set nodemon for development environment

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#8]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Install tsconfig-paths
2. [x] Create nodemon.json file and Set configurations for development environment
2. [x] Change dev scripts in package.json
3. [x] Test it
