### ISSUE TITLE
[Feat]: Create tos validator, tos dto

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#81]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Create tos.validator.ts file
2. [x] Create IsTosCode validator
3. [x] Create tos.dto.ts file
4. [x] Create CreateTosDTO class
