### ISSUE TITLE
[Feat]: Create tos flow - CreateTos

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#82]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create tos.controller.ts file
2. [x] Create and Define tosController
3. [x] Create tos.service.ts file
4. [x] Create and Define tosService
5. [x] Create tos.repository.ts file
6. [x] Create and Define tosRepository
7. [x] Create tos.interceptor.ts file
8. [x] Create and Define tosResponseInterceptor
