### ISSUE TITLE
[Feat]: Create auth flow - signup

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#84]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `3.0h+`
- Priority: `Middle`

### TODO
1. [x] Create user.tos.dto.ts file 
2. [x] Create and Define SignupUserTosDTO, SignupUserTosListDTO
3. [x] Create user.tos.interceptor.ts file
4. [x] Create and Define UserTosListResponseInterceptor
5. [x] Change signup logic so that DB can store the selected terms and conditions by user
