### ISSUE TITLE
[Feat]: Create tos cache

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#86]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Create index.ts file in caches directory
2. [x] Create redis client in index.ts file
3. [x] Create TosCache.cache.ts file
4. [x] Create and Define TosCache
