### ISSUE TITLE
[Refactor]: Refactor tos flow

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#87]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `1.0h`
- Priority: `Middle`

### TODO
1. [x] Refactor TosCache to use public member, tosIds
2. [x] Create pre save hook in Tos Schema
3. [x] Delete findByCode method in TosRepository
4. [x] Delete some codes related to findByCode in createTos method in TosService
