### ISSUE TITLE
[Feat]: Create router with routing-controllers

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#9]
### ISSUE
- Group: `Server`
- Type: `Feat`
- Time: `2.0h`
- Priority: `Middle`

### TODO
1. [x] Install routing-controllers, reflect-metadata, class-transformer and class-validator
2. [x] Create controllers directory and Make basic controller inside of it
3. [x] Apply controllers to server
4. [x] Test it
