### ISSUE TITLE
[Refactor]: Create auth flow - verifyEmail

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#91]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Change the findByEmail method that was used in verifyEmail logic to isDuplicatedEmail method
2. [x] Create isDuplicatedEmail method in UserRepository
3. [x] Create isDuplicatedEmail method in UserCache
