### ISSUE TITLE
[Refactor]: Refactor auth flow - verifyNickName

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#92]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Change the findByNickName method that was used in verifyEmail logic to isDuplicatedNickName method
2. [x] Create isDuplicatedNickName method in UserRepository
3. [x] Create isDuplicatedNickName method in UserCache
