### ISSUE TITLE
[Refactor]: Refactor auth flow - sendMobileCode

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#93]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `0.5h`
- Priority: `Middle`

### TODO
1. [x] Change the findByMobile method that was used in sendMobileCode logic to isDuplicatedMobile method
2. [x] Create isDuplicatedMobile method in UserRepository
3. [x] Create isDuplicatedMobile method in UserCache
