### ISSUE TITLE
[Refactor]: Refactor auth flow - signup

### ISSUE THREAD

**Issue by shoepro** [shoepro/server#95]
### ISSUE
- Group: `Server`
- Type: `Refactor`
- Time: `1.5h`
- Priority: `Middle`

### TODO
1. [x] Create and Define TosCache in tos.cache.ts file
2. [x] Optimize UserCache to save data faster
3. [x] Remove the index of name property in TosModel
4. [x] Refactor findAllByCodes method in TosRepository
5. [x] Optimize UserRepository to save and return data faster
6. [x] Optimize signup method in AuthService to save and return data faster
